update checks

diff --git a/src/usr/lib/ocie/include/config/apache b/src/usr/lib/ocie/include/config/apache
--- a/src/usr/lib/ocie/include/config/apache
+++ b/src/usr/lib/ocie/include/config/apache
@@ -94,20 +94,19 @@ else
 fi;
     
 # Test config and print results
-echo "Ocie Config: Data directory for application is ${APP_DATA}";
-HTTPD_CFG=$(ociectl --test);
-if [[ ! -z "${HTTPD_CFG}" ]];then
-    echo "Ocie Config: Test FAILED, reverting changes";
-    echo "Ocie Config: Result: ${HTTPD_CFG}";
-    reset_config;
-    exit 1;
-fi;
-    
-# Tomcat sources this config, only print if apache
+# Tomcat sources this script, only print if apache
 if [[ ! "${APP_TYPE}" == "tomcat" ]];then
-    echo "#Apache Initialized" > ${OCIE_HOME}/conf/ocie-apache.init;
+    HTTPD_CFG=$(ociectl --test);
+    if [[ ! -z "${HTTPD_CFG}" ]];then
+        echo "Ocie Config: Test FAILED, reverting changes";
+        echo "Ocie Config: Result: ${HTTPD_CFG}";
+        reset_config;
+        exit 1;
+    fi;
+    echo "Ocie Config: Data directory for application is ${APP_DATA}";
     echo "Ocie Config: Apache Config Test PASSED, using updated configuration";
     echo "Ocie Config: Apache2 remoteip configured with [address: ${VADC_IP_ADDRESS}, header: ${VADC_IP_HEADER}]";
     echo "Ocie Config: Initialization complete"
     echo "Ocie Config: You can run the app as [ ${APP_RUNAS} ] OR risk it for the biscuit and run as root";
 fi;
+echo "#Apache Initialized" > ${OCIE_HOME}/conf/ocie-apache.init;
